In [1]:
import pandas as pd 

data = pd.read_excel('1128_유사도_ver01.xlsx')
data.drop(['Unnamed: 0'],axis=1,inplace=True)
data.head()

brand   product        거품        두피       머릿결       세정력        탈모  \
0     TS      BD샴푸  2.186275  2.176471  2.024510  2.044118  2.509804   
1     TS    올뉴TS샴푸  2.186275  2.176471  2.024510  2.044118  2.509804   
2     TS  프리미엄TS샴푸  2.260870  2.130435  1.782609  2.000000  2.739130   
3  닥터그루트   손상모발용샴푸       NaN       NaN       NaN       NaN       NaN   
4  닥터그루트   지성두피용샴푸       NaN       NaN       NaN       NaN       NaN   

          향  가격(500ml)                                        ingredients  \
0  2.191176    15000.0    정제수    다이소듐라우레스설포석시네이트    라우릴글루코사이드    코카마이드...   
1  2.191176    12900.0    정제수    소듐라우릴설페이트    어성초추출물    약모밀추출물    소듐라우...   
2  2.043478    15290.0    바이오틴    니코틴산아마이드    덱스판테놀    피리티온아연액    디나트륨...   
3       NaN    28625.0    덱스판테놀    니코틴산아미드    살리실산    폴리옥시에틸렌경화피마자유   ...   
4       NaN    28625.0    덱스판테놀    니코틴산아미드    살리실산    시트르산    식초    폴리...   

                                     ingredients_ten  
0  정제수 다이소듐라우레스설포석시네이트 라우릴글루코사이드 코카마이드메틸엠이에이 코카미도...  
1  정제수 소듐라우릴설페이트 어성초추출물 약모밀추출물 소듐라우레스설페이트 코카미도프로필...  
2  바이오틴 니코틴산아마이드 덱스판테놀 피리티온아연액 디나트륨이디티에이 구아하이드록시프...  
3  덱스판테놀 니코틴산아미드 살리실산 폴리옥시에틸렌경화피마자유 폴리옥시에틸렌펜타에리스리...  
4  덱스판테놀 니코틴산아미드 살리실산 시트르산 식초 폴리옥시에틸렌경화피마자유 폴리옥시에...

In [2]:
import copy 
data2 = copy.deepcopy(data)

In [3]:
import re
 
def cleanText(readData):
    #텍스트에 포함되어 있는 특수 문자 제거 
    text = re.sub('[;-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', ' ', readData)
    return text

### 코사인 유사도 테스트 코드

In [ ]:
sample1 = '정제수 디소듐라우레스설포석시네이트 코카미도프로필베타인 코카마이드미파'
sample2 = '정제수 디소듐라우레스설포석시네이트 코카미도프로필베타인 코카마이드미파 피이지-7글리세릴코코에이트' 
sample3 = '코카미도프로필베타인 코카마이드미파 피이지-7글리세릴코코에이트 부틸렌글라이콜 피이지-150 디스테아레이트 향료 드럼스틱나무씨추출물'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

count_vect_test = CountVectorizer(min_df=0, ngram_range=(1,2))
ingredient_mat_test = count_vect_test.fit_transform([sample1,sample2,sample3])
print(ingredient_mat_test.shape)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

ingredient_sim_test = cosine_similarity(ingredient_mat_test, ingredient_mat_test)
print(ingredient_sim_test.shape)

In [ ]:
ingredient_sim_test

In [4]:
data2['ingredients'][3] 

'  덱스판테놀    니코틴산아미드    살리실산    폴리옥시에틸렌경화피마자유    폴리옥시에틸렌펜타에리스리틸테트라스테아레이트    식초    멘톨    카라멜    디메틸디알릴암모늄클로라이드    아크릴아마이드코폴리머솔루션    글리세린    헥실렌글리콜    시트르산    어성초추출물    디알킬    12    13    말레이트    하수오추출물    상황버섯추출물    박하잎추출물    테트라나트륨이디티에이    벤조산나트륨    2    아미노    2    메틸    1    프로파놀    조합향    hampoo    39526    편백추출물    폴리옥시에틸렌글리세릴모노코코에이트    7    코카마이드메칠엠이에이    정제소금    조합향    158591    조합향    avender8539220    홍삼추출물    창포엑스    코카미도프로필베타인    디소듐라우레스설포석시네이트액    정제수  '

In [ ]:
data2['ingredients'].isnull().sum()

In [ ]:
num = 0 
count = 0
for ingredient in data2['ingredients']:
    if 'nan' in ingredient:
        count += 1 
    num += 1 
    
print(count)

In [ ]:
data2.head()

In [ ]:
import re 

s = re.compile('[가-히a-z0-9]+')
sample = s.findall("      nan    ")
if 'nan ' in sample:
    print('p')

In [ ]:
data2['ingredients'].dropna()

### 상위 성분 10~15개 추출

In [21]:
import re 

s = re.compile('[가-히a-z]+')

num = 0

for ingredients in data2['ingredients']:
    ingredients_2 = s.findall(ingredients)
    data2['ingredients'][num] =  cleanText(str(ingredients_2))
    num += 1

/home/daehynk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [ ]:
data2.shape

In [22]:
# 상위 열개 성분만 칼럼으로 따로 생성 

import re 

num = 0
for ingredients in data2['ingredients']:
    str_list = ingredients.split()
    data2['ingredients_ten'][num] = ' '.join(str_list[:15])
    num += 1 

/home/daehynk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [24]:
data2['ingredients_ten'][1]

'정제수 소듐라우릴설페이트 어성초추출물 약모밀추출물 소듐라우레스설페이트 코카미도프로필베타인 코카마이드디이에이 글리세린 징크피리치온 소듐클로라이드 소듐벤조에이트 세테아릴알코올 판테놀 자소엽추출물 소엽잎추출물'

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(min_df=0, ngram_range=(0,15))
ingredient_mat = count_vect.fit_transform(data2['ingredients_ten'])
print(ingredient_mat.shape)

(273, 25532)


In [99]:
count_vect.vocabulary_

{'': 0,
 '정제수': 16249,
 '다이소듐라우레스설포석시네이트': 2721,
 '라우릴글루코사이드': 5371,
 '코카마이드메틸엠이에이': 19870,
 '코카미도프로필베타인': 20341,
 '부틸렌글라이콜': 7727,
 '소듐라우로일메틸이세티오네이트': 10729,
 '글리세린': 1476,
 '폴리쿼터늄': 23294,
 '다이포타슘글리시리제이트': 3309,
 '주아나무껍질추출물': 19030,
 '토코페릴아세테이트': 22529,
 '멘톨': 6739,
 '헥산다이올': 25258,
 '카프릴릴글라이콜': 19574,
 '정제수 다이소듐라우레스설포석시네이트': 16288,
 '다이소듐라우레스설포석시네이트 라우릴글루코사이드': 3008,
 '라우릴글루코사이드 코카마이드메틸엠이에이': 5450,
 '코카마이드메틸엠이에이 코카미도프로필베타인': 19905,
 '코카미도프로필베타인 부틸렌글라이콜': 20939,
 '부틸렌글라이콜 소듐라우로일메틸이세티오네이트': 7767,
 '소듐라우로일메틸이세티오네이트 글리세린': 10739,
 '글리세린 폴리쿼터늄': 1959,
 '폴리쿼터늄 다이포타슘글리시리제이트': 23305,
 '다이포타슘글리시리제이트 주아나무껍질추출물': 3310,
 '주아나무껍질추출물 토코페릴아세테이트': 19031,
 '토코페릴아세테이트 멘톨': 22530,
 '멘톨 헥산다이올': 6831,
 '헥산다이올 카프릴릴글라이콜': 25268,
 '정제수 다이소듐라우레스설포석시네이트 라우릴글루코사이드': 16492,
 '다이소듐라우레스설포석시네이트 라우릴글루코사이드 코카마이드메틸엠이에이': 3009,
 '라우릴글루코사이드 코카마이드메틸엠이에이 코카미도프로필베타인': 5451,
 '코카마이드메틸엠이에이 코카미도프로필베타인 부틸렌글라이콜': 19906,
 '코카미도프로필베타인 부틸렌글라이콜 소듐라우로일메틸이세티오네이트': 20940,
 '부틸렌글라이콜 소듐라우로일메틸이세티오네이트 글리세린': 7768,
 '소듐라우로일메틸이세티오네이트 글리세린

In [100]:
from sklearn.metrics.pairwise import cosine_similarity

ingredient_sim = cosine_similarity(ingredient_mat, ingredient_mat)
print(ingredient_sim.shape)
#print(ingredient_sim[:1])

(273, 273)


In [101]:
ingredient_sim_sorted_ind = ingredient_sim.argsort()[:, ::-1]
#print(ingredient_sim_sorted_ind[2,])

In [102]:
def find_sim_product(df, sorted_ind, product, top_n=6):
    
    product_name = df[df['product'] == product]
    product_index = product_name.index.values
    similar_indexes = sorted_ind[product_index, :(top_n)]
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [103]:
similar_movies = find_sim_product(data2, ingredient_sim_sorted_ind,'아쿠아에스링 퓨어 리프레싱 헤어 케어',10)
similar_movies[['brand','product','가격(500ml)' ,'ingredients_ten']]

[[161 130 187 129 247 169 115 268 246 271]]


brand               product     가격(500ml)  \
161  아쿠아더마  아쿠아에스링 퓨어 리프레싱 헤어 케어  34570.000000   
130   세바메드                리페어 샴푸  80000.000000   
187   이브로쉐             인텐스 샤인 샴푸  33000.000000   
129   사이오스        올레오12 인텐스케어 샴푸   3933.333333   
247  하이앙포레               프리미엄 샴푸  17500.000000   
169   엘라스틴         실크리페어 리커버리 샴푸   3950.000000   
115     바론           모링가 리프레쉬 샴푸   7450.000000   
268  착한팩토리           밀크단백질 90 샴푸   7500.000000   
246  하이앙포레              시크릿 학생샴푸  23333.333333   
271  착한팩토리                더 빠른샴푸  23000.000000   

                                       ingredients_ten  
161  정제수 소듐 올레핀설포네이트 코카마이드디이에이 코카미도프로필베타인 피이지 디메치콘 ...  
130  정제수 소듐 올레핀설포네이트 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트...  
187  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 캐모마일꽃수...  
129  정제수 소듐라우레스설페이트 코카미도프로필베타인 소듐클로라이드 디소듐코코암포디아세테이...  
247  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 피이지 하이...  
169  정제수 소듐라우레스설페이트 코카미도프로필베타인 글라이콜디스테아레이트 글라이콜다이스테...  
115  정제수 코코 글루코사이드 소듐코코일이세치오네이트 소듐코코일이세티오네이트 소듐코코일글...  
268  디소듐라우레스설포석시네이트 우유단백질추출물 코카마이드미파 코카미도프로필베타인 정제수...  
246  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 피이지 하이...  
271  정제수 폴리쿼터늄 디소듐이디티에이 시트릭애씨드 판테놀 피이지 디스테아레이트 코카마이...

In [104]:
# 코사인 유사도 수치 
ingredient_sim[161,[ 130 ,187 ,129 ,247 ,169 ,115 ,268 ,246 ,271]]

array([0.7037037, 0.7010582, 0.7000097, 0.7000097, 0.6984127, 0.6984127,
       0.6984127, 0.6984127, 0.6984127])

In [66]:
similar_movies['cosine_similarity'] = 0 

/home/daehynk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [68]:
# 코사인 유사도 수치 
cos = ingredient_sim[161,[130 ,187, 129, 247, 169, 115, 268, 246, 271]]

In [74]:
similar_movies = find_sim_product(data2, ingredient_sim_sorted_ind,'텐더피오니 샴푸',10)
similar_movies[['brand','product','가격(500ml)' ,'ingredients_ten']]

[[ 32 264 254 261  83 260 134 262 265 263]]


brand                              product  가격(500ml)  \
32    드라세나                             텐더피오니 샴푸    66250.0   
264  헤어플러스                             실크 코팅 샴푸    18000.0   
254    해리치                   베다셀 헤어 프로그램 스칼프 샴푸    30000.0   
261  헤어플러스                        벨벳 데미지 리페어 샴푸    15000.0   
83      로픈                      바오밥 프리미엄 약산성 샴푸    12450.0   
260  헤어플러스                             더 리컬리 샴푸    24800.0   
134   세바메드                             에브리데이 샴푸    75000.0   
262  헤어플러스  벨벳 프로틴 본드 샴푸(뉴트리 인젝션 단백질 본드 샴푸/약산성)    24800.0   
265  헤어플러스                         오프레시 딥 허벌 샴푸    25000.0   
263  헤어플러스                           비타 서플라이 샴푸    18000.0   

                                       ingredients_ten  
32   하이드롤라이즈드실크 정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 ...  
264  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...  
254  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 글리세린 코카미도프로...  
261  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...  
83   정제수 코카미도프로필베타인 글리세린 디프로필렌글라이콜 다이프로필렌글라이콜 디소듐코코...  
260  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...  
134  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 소듐라우릴설포아세테이...  
262  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...  
265  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...  
263  정제수 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트 코카미도프로필베타인 ...

In [75]:
# 코사인 유사도 수치 
ingredient_sim[161,[ 264 ,254, 261 , 83 ,260 ,134 ,262 ,265 ,263]]

array([0.68700507, 0.68700507, 0.68435254, 0.68700507, 0.68435254,
       0.69047619, 0.68783069, 0.68435254, 0.68435254])

In [71]:
index_list = []
for num in similar_movies.index:
    index_list.append(num)

In [67]:
for num in cos:
    similar_movies['cosine_similarity']

brand               product        거품        두피       머릿결       세정력  \
161  아쿠아더마  아쿠아에스링 퓨어 리프레싱 헤어 케어  2.607143  2.500000  2.482143  2.214286   
130   세바메드                리페어 샴푸       NaN       NaN       NaN       NaN   
187   이브로쉐             인텐스 샤인 샴푸  2.050000  1.850000  2.300000  2.100000   
129   사이오스        올레오12 인텐스케어 샴푸  2.030928  2.072165  2.113402  2.006873   
247  하이앙포레               프리미엄 샴푸  2.205479  2.417808  2.178082  2.178082   
169   엘라스틴         실크리페어 리커버리 샴푸  2.052632  2.023923  2.143541  2.014354   
115     바론           모링가 리프레쉬 샴푸  2.300000  2.200000  2.200000  2.100000   
268  착한팩토리           밀크단백질 90 샴푸       NaN       NaN       NaN       NaN   
246  하이앙포레              시크릿 학생샴푸       NaN       NaN       NaN       NaN   
271  착한팩토리                더 빠른샴푸       NaN       NaN       NaN       NaN   

           탈모         향     가격(500ml)  \
161  2.160714  2.767857  34570.000000   
130       NaN       NaN  80000.000000   
187  2.050000  2.500000  33000.000000   
129  2.010309  2.278351   3933.333333   
247  2.089041  2.308219  17500.000000   
169  2.019139  2.545455   3950.000000   
115  2.000000  2.300000   7450.000000   
268       NaN       NaN   7500.000000   
246       NaN       NaN  23333.333333   
271       NaN       NaN  23000.000000   

                                           ingredients  \
161    정제수    소듐    올레핀설포네이트    코카마이드디이에이    코카미도프로...   
130    정제수    소듐    올레핀설포네이트    다이소듐라우레스설포석시네이트    ...   
187    정제수    소듐라우레스설페이트    코카미도프로필베타인    피이지    글리...   
129    정제수    소듐라우레스설페이트    코카미도프로필베타인    소듐클로라이드  ...   
247    정제수    소듐라우레스설페이트    코카미도프로필베타인    피이지    글리...   
169    정제수    소듐라우레스설페이트    코카미도프로필베타인    글라이콜디스테아레...   
115    정제수    코코    글루코사이드    소듐코코일이세치오네이트    소듐코코일...   
268    디소듐라우레스설포석시네이트    우유단백질추출물    코카마이드미파    코카미...   
246    정제수    소듐라우레스설페이트    코카미도프로필베타인    피이지    글리...   
271    정제수    폴리쿼터늄    디소듐이디티에이    시트릭애씨드    판테놀   ...   

                                       ingredients_ten  cosine_similarity  
161  정제수 소듐 올레핀설포네이트 코카마이드디이에이 코카미도프로필베타인 피이지 디메치콘 ...                  0  
130  정제수 소듐 올레핀설포네이트 다이소듐라우레스설포석시네이트 디소듐라우레스설포석시네이트...                  0  
187  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 캐모마일꽃수...                  0  
129  정제수 소듐라우레스설페이트 코카미도프로필베타인 소듐클로라이드 디소듐코코암포디아세테이...                  0  
247  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 피이지 하이...                  0  
169  정제수 소듐라우레스설페이트 코카미도프로필베타인 글라이콜디스테아레이트 글라이콜다이스테...                  0  
115  정제수 코코 글루코사이드 소듐코코일이세치오네이트 소듐코코일이세티오네이트 소듐코코일글...                  0  
268  디소듐라우레스설포석시네이트 우유단백질추출물 코카마이드미파 코카미도프로필베타인 정제수...                  0  
246  정제수 소듐라우레스설페이트 코카미도프로필베타인 피이지 글리세릴코코에이트 피이지 하이...                  0  
271  정제수 폴리쿼터늄 디소듐이디티에이 시트릭애씨드 판테놀 피이지 디스테아레이트 코카마이...                  0

In [ ]:
data.iloc[]

In [ ]:
from scipy import spatial

spatial.distance.cosine()

In [ ]:
similar_movies = find_sim_product(data2, ingredient_sim_sorted_ind,'텐더피오니 샴푸',6)
similar_movies[['brand','product','가격(500ml)' ,'ingredients','bad_score']]

## 나쁜 성분 갯수 표현 

In [ ]:
bad_ingredients = ['리모넨','페녹시에탄올', '유제놀', '피이지-12다이메티콘', '피이지-60', '피이지-40', '피이지-45M', '피이지-45M', '피이지-60', '청색1호', '황색203호', '피이지-12', '피이지-150펜타에리스리틸테트라스테아레이트', '알파-이소메칠이오논','향료', '헥실신나몰','피이지-7글리세릴코코에이트', '피이지-14M', '페녹시에탄올', '메칠파라벤', '황색4호', '리날룰', '신남알', '피이지-12다이메티콘', '피이지-8', '알파-이소메칠이오논', '벤질알코올' ,'황색5호', '리날룰,피이지-12', '피이지-12', '청색1호', '헥실신나몰','황색203호', '적색227호', '헥실신나몰', '황색5호', '리날룰', '피이지-32', '피이지-40하이드로제네이티드캐스터오일', '피이지-7글리세릴코코에이트', '황색4호', '피이지-7글리세릴코코에이트', '알파-이소메칠이오논','황색203호', '황색5호', '소듐라우레스설페이트', '피이지-8', '리날룰', '벤질알코올', '피이지-150', '녹색3호', '리모넨', '신남알','황색203호', '알파-이소메칠이오논', '유제놀','청색1호', '피이지-6', '벤질알코올','황색203호', '리모넨','황색203호', '벤질알코올','피이지-150', '향료']

In [ ]:
bad_ingredients2 = list(set(bad_ingredients))

In [ ]:
len(bad_ingredients2)

In [ ]:
data2['bad_score'] = 0

In [ ]:
data2.head()

In [ ]:
num = 0
for ingredients in data2['ingredients']:
    score = 0
    for ingredient in ingredients.split(' '):
        for bad_ingredient in bad_ingredients2:    
            if bad_ingredient in ingredient: 
                score += 1
    data2['bad_score'][num] = score 
    num += 1   

In [ ]:
data2['bad_score'].value_counts()

In [ ]:
data2.to_excel('1127_가격+성분_최종_ver0222.xlsx')