In [1]:
import pandas as pd

In [2]:
sample = pd.read_excel('excel_02_1018_1단계_CJ_review_peprocessing.xlsx')
sample.head()

Unnamed: 0              product  \
0           0  허벌에센스 핑크로즈 샴푸 490ml   
1           1  허벌에센스 핑크로즈 샴푸 490ml   
2           2  허벌에센스 핑크로즈 샴푸 490ml   
3           3  허벌에센스 핑크로즈 샴푸 490ml   
4           4  허벌에센스 핑크로즈 샴푸 490ml   

                                              review        거품      세정력  \
0    기존에 상품대비 가격이 부담이었는데 할인율이 높아져서 만족하면서 사용하고 있어요...     보통이에요  아주 만족해요   
1  뽀득뽀득해요 성분 좋다는 샴푸 쓰다가 거품도 너무 안나고 세정력이 떨어져서 바꿔봤는...  거품이 풍성해요    보통이에요   
2                            매번쓰던거입니다 거품도풍넝하고맘에아두듭니다  거품이 풍성해요  아주 만족해요   
3                  노란색 사용하다가 핑크색이 향이 더 좋을것 같아서 구매했어요  거품이 풍성해요    보통이에요   
4  비누와 같은 세정력 세장력은 좋은 것 같은데 샴푸 후 머릿결이 조금 뻣뻣한 느낌이 ...  거품이 풍성해요    보통이에요   

        자극도        향  
0     보통이에요    보통이에요  
1  자극없이 순해요  아주 만족해요  
2  자극없이 순해요  아주 만족해요  
3  자극없이 순해요    보통이에요  
4  자극없이 순해요    보통이에요

In [3]:
sample.drop(['Unnamed: 0'],axis='columns' , inplace = True)

In [4]:
sample.head()

product                                             review  \
0  허벌에센스 핑크로즈 샴푸 490ml    기존에 상품대비 가격이 부담이었는데 할인율이 높아져서 만족하면서 사용하고 있어요...   
1  허벌에센스 핑크로즈 샴푸 490ml  뽀득뽀득해요 성분 좋다는 샴푸 쓰다가 거품도 너무 안나고 세정력이 떨어져서 바꿔봤는...   
2  허벌에센스 핑크로즈 샴푸 490ml                            매번쓰던거입니다 거품도풍넝하고맘에아두듭니다   
3  허벌에센스 핑크로즈 샴푸 490ml                  노란색 사용하다가 핑크색이 향이 더 좋을것 같아서 구매했어요   
4  허벌에센스 핑크로즈 샴푸 490ml  비누와 같은 세정력 세장력은 좋은 것 같은데 샴푸 후 머릿결이 조금 뻣뻣한 느낌이 ...   

         거품      세정력       자극도        향  
0     보통이에요  아주 만족해요     보통이에요    보통이에요  
1  거품이 풍성해요    보통이에요  자극없이 순해요  아주 만족해요  
2  거품이 풍성해요  아주 만족해요  자극없이 순해요  아주 만족해요  
3  거품이 풍성해요    보통이에요  자극없이 순해요    보통이에요  
4  거품이 풍성해요    보통이에요  자극없이 순해요    보통이에요

In [5]:
sample.columns

Index(['product', 'review', '거품', '세정력', '자극도', '향'], dtype='object')

In [6]:
product_all = sample['product'].value_counts()

In [7]:
product_all.shape # 172개의 제품이 있다.

(172,)

In [8]:
product_all.shape[0]

172

In [15]:
count = 0
for product in product_all:
    if count <10:
        print(product)
    count += 1

990
990
953
941
801
717
680
671
669
561


In [10]:
product = list(sample['product'].unique())

In [11]:
product

['허벌에센스 핑크로즈 샴푸 490ml',
 '려 함빛 극손상케어',
 '세바메드 베이비 칠드런스 샴푸 150ml',
 '로레알파리 토탈리페어5 샴푸 450ml',
 '로레알파리 폴 리페어 샴푸 450ml',
 '바티스트 드라이샴푸 블러쉬 200ml',
 '바티스트 드라이샴푸 블러쉬 50ml',
 '바티스트 드라이샴푸 오리지널 200ml',
 '려 자양윤모두피딥클렌저145ML',
 '로레알파리 케라틴 스무드 샴푸',
 '바티스트 드라이샴푸 후레쉬 200ml',
 '바티스트 드라이샴푸 오리지널 50ml',
 '츠바키 엑스트라 모이스트 샴푸 500ml',
 '츠바키 데미지케어 샴푸 500ml',
 '츠바키 데미지케어 2종 세트(샴푸 리필345ml추가증정)',
 '츠바키 볼륨터치 샴푸 500ml',
 '츠바키 볼륨터치 2종 세트(샴푸 리필345ml추가증정)',
 '미쟝센 데미지케어 샴푸 530ml',
 '라우쉬 스위스 허벌 케어 샴푸 200ml(수분 진정 샴푸)',
 '라우쉬 하트씨드 센시티브 샴푸 200ml(민감 두피 진정 샴푸)',
 '라우쉬 콜츠푸트 안티-댄드러프 샴푸 200ml(비듬 두피 정화 샴푸)',
 '라우쉬 씨위드 디그리징 샴푸 200ml 기획 (지성 두피 청정 샴푸)',
 '라우쉬 에그오일 너리싱 샴푸 200ml(건성 영양 샴푸)',
 '라우쉬 카모마일-아마란스 리페어 샴푸 200ml(극손상케어 샴푸)',
 '라우쉬 아보카도 컬러-프로텍팅 샴푸 200ml(펌염색 보호 샴푸)',
 '로레알파리 엑스트라오디네리 오일 샴푸',
 '클로란 퀴닌 비타민B 샴푸400ml 가늘고 힘 없는 두피·모발용',
 '클로란 망고버터 뉴트리션 샴푸 400ml 건조 손상 두피·모발용',
 '클로란 피오니 샴푸 400ml 민감 두피·모발용',
 '클로란 오트밀크 울트라 젠틀 샴푸 400ml 모든 두피·모발용',
 '라우쉬 윌로우바크 트리트먼트 샴푸 200ml 기획(모근 모발 강화 샴푸)',
 '바티스트 드라이샴푸 체리 200ml',
 '[온라인단독]바티스트 드라이샴푸 체리 5

In [14]:
product[0][:10]

'허벌에센스 핑크로즈'

In [20]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
encoder = LabelEncoder()
encoder.fit(product)
labels = encoder.transform(product)
# 2차원 데이터로 변환합니다. 
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다. 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(172, 172)


/home/daehynk/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [21]:
import pandas as pd

df = pd.DataFrame({'product':product})
pd.get_dummies(df)

product_NEW 존프리다 브릴리언트 브루넷 컬러 프로텍팅 모이스춰라이징 샴푸(수분공급/컬러유지)  \
0                                                    0          
1                                                    0          
2                                                    0          
3                                                    0          
4                                                    0          
..                                                 ...          
167                                                  0          
168                                                  0          
169                                                  0          
170                                                  0          
171                                                  0          

     product_TS BD샴푸 500g  product_TS 프리미엄 샴푸 300ml*2+100ml 기획  \
0                       0                                    0   
1                       0                                    0   
2                       0                                    0   
3                       0                                    0   
4                       0                                    0   
..                    ...                                  ...   
167                     0                                    0   
168                     0                                    0   
169                     0                                    0   
170                     0                                    0   
171                     0                                    0   

     product_TS 프리미엄 샴푸 300ml2+100ml 기획  \
0                                     0   
1                                     0   
2                                     0   
3                                     0   
4                                     0   
..                                  ...   
167                                   0   
168                                   0   
169                                   0   
170                                   0   
171                                   0   

     product_TS 프리미엄 샴푸 330g(300g+6g*5매) NEW  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
..                                       ...   
167                                        0   
168                                        0   
169                                        0   
170                                        0   
171                                        0   

     product_[아로마티카] 로즈마리 스칼프 스케일링  샴푸 400ml  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
..                                       ...   
167                                        0   
168                                        0   
169                                        0   
170                                        0   
171                                        0   

     product_[아로마티카] 티트리 퓨리파잉 샴푸 400ml  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   
..                                 ...   
167                                  0   
168                                  0   
169                                  0   
170                                  0   
171                                  0   

     product_[온라인단독] 닥터포헤어 폴리젠 샴푸 500ml*2개입 기획  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4    

In [88]:
product_all # 로우 갯수가 60개 이상부터는 중간 생략되서 나온다. 

[온라인단독] 아로마티카 로즈마리 스케일링 샴푸 900ml           990
[아로마티카] 로즈마리 스칼프 스케일링  샴푸 400ml            990
라우쉬 콜츠푸트 안티-댄드러프 샴푸 200ml(비듬 두피 정화 샴푸)     953
허벌에센스 핑크로즈 샴푸 490ml                        941
사이오스 실리콘프리 안티댄드러프 샴푸 750ml                 801
                                          ... 
[온라인단독] 존프리다 프리즈이즈 3종 트래블키트                  1
[온라인단독]미쟝센 데미지케어샴푸 680ml                     1
피토더마 쿨링 샴푸 550ml                             1
[온라인단독]아로마티카 로즈마리 스칼프 스케일링 샴푸 900ml(리필)      1
더마앤모어 미셀라 안티더스트 두피 샴푸 600ml                  1
Name: product, Length: 172, dtype: int64

In [48]:
product_all.head(20) # columns 수를 내림차순으로 정렬된다.

[온라인단독] 아로마티카 로즈마리 스케일링 샴푸 900ml            990
[아로마티카] 로즈마리 스칼프 스케일링  샴푸 400ml             990
라우쉬 콜츠푸트 안티-댄드러프 샴푸 200ml(비듬 두피 정화 샴푸)      953
허벌에센스 핑크로즈 샴푸 490ml                         941
사이오스 실리콘프리 안티댄드러프 샴푸 750ml                  801
사이오스 실리콘무첨가 리페어 샴푸 750ml                    717
닥터포헤어 씨솔트 스케일러 200g                         680
바티스트 드라이샴푸 오리지널 200ml                       671
츠바키 데미지케어 2종 세트(샴푸 리필345ml추가증정)             669
라우쉬 윌로우바크 트리트먼트 샴푸 200ml 기획(모근 모발 강화 샴푸)    561
바티스트 드라이샴푸 후레쉬 200ml                        467
[온라인단독] 클로란 퀴닌 샴푸 400ml 2+1                 410
바티스트 드라이샴푸 오리지널 50ml                        404
[아로마티카] 티트리 퓨리파잉 샴푸 400ml                   397
프레시팝 두피클렌징(그린허브 모히또) 샴푸 500ML               358
팬틴 극손상 샴푸 500ml                             339
츠바키 오일 엑스트라 인텐시브 데미지 케어 샴푸 450ml            335
허벌에센스 클래식 카모마일 샴푸 490ml                     314
로레알파리 토탈리페어5 샴푸 450ml                       310
사이오스 올레오12 인텐스케어 샴푸 750ml                   291
Name: product, dtype: int64

In [50]:
# head는 인덱싱이 안된다. 그래서 중간부터 보거나 하려면 iloc 써서 보자. 
product_all.iloc[140:]

[온라인단독] 달리프 클로렐라 베러 루트 릴렉싱샴푸 500ml*2개 (1+1기획세트)        5
이브로쉐 컬러 프로텍션 & 래디언스 샴푸 50ML (Lo)                       5
려 자양윤모두피딥클렌저145ML                                      5
더프트앤도프트 소피소피 샴푸 트리트먼트 기획 세트                            4
닥터그루트 지성두피용 샴푸 400ml                                   4
[온라인단독] 클로란 퀴닌 샴푸  400ml*2 +헤어 브러쉬 기획                  4
[온라인단독] 클로란 퀴닌 샴푸 400ml*2 +헤어 브러쉬 기획                   3
투쿨포스쿨 에그레미디 팩 샴푸                                       3
[온라인단독]록시땅 아로마 리페어 샴푸 500ml                            3
려 청아두피딥.샴푸 400G2                                       3
[온라인단독]록시땅 아로마 리페어 샴푸 300ml                            3
려 자양윤모 중건성용 샴푸 400ML                                   3
아베다 데미지 레미디™ 리스트럭처링 샴푸 250ml                           3
아베다 샴퓨어™ 드라이 샴푸 56g                                    2
이브로쉐 오트 샴푸 50ML (Lo)                                   2
아로마티카 로즈마리 스칼프 스케일링 샴푸 900ml리필온                        2
세바메드 칠드런스 샴푸 150ml                                     2
[온라인단독]미쟝센 퍼펙트 리페어 샴푸 680ML    